=== NYULibraries/aco-mets/f2f-docs/one-ie-to-many-source-parent_mets.dtd
<!ELEMENT mdRef (#PCDATA)>
<!ATTLIST mdRef LOCTYPE CDATA #IMPLIED>
<!ATTLIST mdRef MDTYPE CDATA #IMPLIED>
<!ATTLIST mdRef OTHERMDTYPE CDATA #IMPLIED>
<!ATTLIST mdRef CHECKSUM CDATA #IMPLIED>
<!ATTLIST mdRef CHECKSUMTYPE CDATA #IMPLIED>
<!ATTLIST mdRef xlink:href CDATA #IMPLIED>
<!ELEMENT mods:scriptTerm (#PCDATA)>
<!ATTLIST mods:scriptTerm type CDATA #IMPLIED>
<!ELEMENT mods:recordInfo (#PCDATA | mods:languageOfCataloging)*>
<!ELEMENT dmdSec (#PCDATA | mdWrap)*>
<!ATTLIST dmdSec ID CDATA #IMPLIED>
<!ELEMENT xmlData (#PCDATA | mods:recordInfo)*>
<!ELEMENT div (#PCDATA | div | mptr)*>
<!ATTLIST div DMDID CDATA #IMPLIED>
<!ATTLIST div TYPE CDATA #IMPLIED>
<!ATTLIST div ID CDATA #IMPLIED>
<!ELEMENT fileSec (#PCDATA | fileGrp)*>
<!ELEMENT mptr (#PCDATA)>
<!ATTLIST mptr LOCTYPE CDATA #IMPLIED>
<!ATTLIST mptr xlink:href CDATA #IMPLIED>
<!ELEMENT fileGrp (#PCDATA | file)*>
<!ATTLIST fileGrp USE CDATA #IMPLIED>
<!ELEMENT FLocat (#PCDATA)>
<!ATTLIST FLocat LOCTYPE CDATA #IMPLIED>
<!ATTLIST FLocat xlink:href CDATA #IMPLIED>
<!ELEMENT mdWrap (#PCDATA | xmlData)*>
<!ATTLIST mdWrap MDTYPE CDATA #IMPLIED>
<!ELEMENT mods:languageTerm (#PCDATA)>
<!ELEMENT file (#PCDATA | FLocat)*>
<!ATTLIST file USE CDATA #IMPLIED>
<!ATTLIST file ID CDATA #IMPLIED>
<!ATTLIST file CHECKSUM CDATA #IMPLIED>
<!ATTLIST file CHECKSUMTYPE CDATA #IMPLIED>
<!ATTLIST file MIMETYPE CDATA #IMPLIED>
<!ELEMENT mods:languageOfCataloging (#PCDATA | mods:languageTerm | mods:scriptTerm)*>
<!ELEMENT amdSec (#PCDATA | digiprovMD)*>
<!ELEMENT mets (#PCDATA | dmdSec | amdSec | fileSec | structMap)*>
<!ATTLIST mets xsi:schemaLocation CDATA #IMPLIED>
<!ATTLIST mets ID CDATA #IMPLIED>
<!ATTLIST mets LABEL CDATA #IMPLIED>
<!ATTLIST mets OBJID CDATA #IMPLIED>
<!ATTLIST mets PROFILE CDATA #IMPLIED>
<!ATTLIST mets TYPE CDATA #IMPLIED>
<!ELEMENT digiprovMD (#PCDATA | mdRef)*>
<!ATTLIST digiprovMD ID CDATA #IMPLIED>
<!ELEMENT structMap (#PCDATA | div)*>
<!ATTLIST structMap TYPE CDATA #IMPLIED>

=== NYULibraries/aco-mets/examples/ie/ie_mets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mets SYSTEM "file:/Users/jgp/dl/projects/ACO/dev/aco-mets/examples/one-ie-to-many-source-parent_mets.dtd">
<mets xmlns="http://www.loc.gov/METS/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/version191/mets.xsd http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/mods.xsd"
    ID="mets" LABEL="" OBJID="" PROFILE="" xmlns:mods="http://www.loc.gov/mods/v3" TYPE="">
    <metsHdr CREATEDATE="2013-07-29T00:00:00Z" LASTMODDATE="2013-07-29T00:00:00Z" RECORDSTATUS="DRAFT">
        <agent ROLE="CREATOR" TYPE="INDIVIDUAL">
            <name>John Q. Public</name>
        </agent>
        <agent ROLE="DISSEMINATOR" TYPE="ORGANIZATION">
            <name>Princeton University Libraries</name>
        </agent>
    </metsHdr>
    <dmdSec ID="dmd-00000001">
        <mdRef LOCTYPE="URL" MDTYPE="OTHER" OTHERMDTYPE="MARCXML" MIMETYPE="application/xml" CHECKSUMTYPE="SHA-512"
            CHECKSUM="0cf9180a764aba863a67b6d72f0918bc131c6772642cb2dce5a34f0a702f9470ddc2bf125c12198b1995c233c34b4afd346c54a2334c350a948a51b6e8b4e6b6"
            xlink:href="princeton_ie123456_marcxml.xml"/>
    </dmdSec>
    <dmdSec ID="dmd-arab">
        <mdWrap MDTYPE="MODS">
            <xmlData>
                <mods:recordInfo>
                    <mods:languageOfCataloging>
                        <mods:languageTerm>ara</mods:languageTerm>
                        <mods:scriptTerm type="code">Arab</mods:scriptTerm>
                    </mods:languageOfCataloging>
                </mods:recordInfo>
            </xmlData>
        </mdWrap>
    </dmdSec>
    <dmdSec ID="dmd-latin">
        <mdWrap MDTYPE="MODS">
            <xmlData>
                <mods:recordInfo>
                    <mods:languageOfCataloging>
                        <mods:languageTerm/>
                        <mods:scriptTerm/>
                    </mods:languageOfCataloging>
                </mods:recordInfo>
            </xmlData>
        </mdWrap>
    </dmdSec>
    <amdSec ID="amd-00000001">
        <!-- RIGHTS METADATA ARE OPTIONAL BUT amdSec INCLUDED HERE FOR COMPLETENESS. -->
        <rightsMD ID="rmd-00000001">
            <mdRef LOCTYPE="URL" MDTYPE="METSRIGHTS" MIMETYPE="application/xml" CHECKSUMTYPE="SHA-512"
                CHECKSUM="cc06808cbbee0510331aa97974132e8dc296aeb795be229d064bae784b0a87a5cf4281d82e8c99271b75db2148f08a026c1a60ed9cabdb8cac6d24242dac4063"
                xlink:href="princeton_ie123456_rmd.xml"/>
        </rightsMD>
    </amdSec>
    <!-- This fictitious Intellectual Entity comprises intellectual entity sections from two separate source entities -->
    <!-- Source Entity: princeton_aco000123 contains parts of two   distinct intellectual entities -->
    <!--                princeton_aco000124 contains parts of three distinct intellectual entities -->
    <structMap TYPE="INTELLECTUAL_ENTITY">
        <div ID="ie-root" DMDID="dmd-arab dmd-00000001">
            <div TYPE="SOURCE_ENTITIES">
                <div TYPE="SOURCE_ENTITY">
                    <mptr LOCTYPE="URL" xlink:href="princeton_aco000123_mets.xml#struct-ie-00000002"/>
                </div>
                <div TYPE="SOURCE_ENTITY">
                    <mptr LOCTYPE="URL" xlink:href="princeton_aco000124_mets.xml#struct-ie-00000001"/>
                </div>
            </div>
        </div>
    </structMap>
</mets>

=== NYULibraries/aco-mets/examples/one-ie-to-many-source_mets.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mets SYSTEM "file:/Users/jgp/dl/projects/ACO/dev/aco-mets/examples/one-ie-to-many-source-parent_mets.dtd">
<mets xmlns="http://www.loc.gov/METS/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/version191/mets.xsd http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/mods.xsd"
    ID="mets" LABEL="" OBJID="" PROFILE="" xmlns:mods="http://www.loc.gov/mods/v3" TYPE="">
    <dmdSec ID="dmd-0000001"><!-- point to a MARCXML document --></dmdSec>
    <dmdSec ID="dmd-0000002"><!-- point to a different MARCXML document --></dmdSec>
    <dmdSec ID="dmd-arab">
        <mdWrap MDTYPE="MODS">
            <xmlData>
                <mods:recordInfo>
                    <mods:languageOfCataloging>
                        <mods:languageTerm>ara</mods:languageTerm>
                        <mods:scriptTerm type="code">Arab</mods:scriptTerm>
                    </mods:languageOfCataloging>
                </mods:recordInfo>
            </xmlData>
        </mdWrap>
    </dmdSec>
    <dmdSec ID="dmd-latin">
        <mdWrap MDTYPE="MODS">
            <xmlData>
                <mods:recordInfo>
                    <mods:languageOfCataloging>
                        <mods:languageTerm/>
                        <mods:scriptTerm/>
                    </mods:languageOfCataloging>
                </mods:recordInfo>
            </xmlData>
        </mdWrap>
    </dmdSec>
    <amdSec>
        <digiprovMD ID="foo">
            <mdRef LOCTYPE="URL" MDTYPE="OTHER" OTHERMDTYPE="CSV" CHECKSUM="" CHECKSUMTYPE="SHA-512" xlink:href="relative-path-to-environment-of-creation.csv"/>
        </digiprovMD>
    </amdSec>
    <fileSec>
        <fileGrp USE="CALIBRATION">
            <file ID="calibration-00000001" USE="target" CHECKSUM="some-awesome-sha1-hash-value" CHECKSUMTYPE="SHA-512" MIMETYPE="image/tiff">
                <FLocat LOCTYPE="URL" xlink:href="target_m.tif"/>
            </file>
        </fileGrp>
        <fileGrp USE="MASTER">
            <file ID="master-00000001" CHECKSUM="some-awesome-sha1-hash-value" CHECKSUMTYPE="SHA-512" MIMETYPE="image/tiff">
                <FLocat LOCTYPE="URL" xlink:href="master/12345678.tif"/>
            </file>
            <file ID="master-00000002" CHECKSUM="some-awesome-sha1-hash-value" CHECKSUMTYPE="SHA-512" MIMETYPE="image/tiff">
                <FLocat LOCTYPE="URL" xlink:href="master/12345679.tif"/>
            </file>
        </fileGrp>
        <fileGrp USE="DERIVATIVE_MAKER">
            <file ID="derivative_maker-00000001" CHECKSUM="some-awesome-sha1-hash-value" CHECKSUMTYPE="SHA-512" MIMETYPE="image/tiff">
                <FLocat LOCTYPE="URL" xlink:href="derivatives/12345678.tif"/>
            </file>
            <file ID="derivative_maker-00000002" CHECKSUM="some-awesome-sha1-hash-value" CHECKSUMTYPE="SHA-512" MIMETYPE="image/tiff">
                <FLocat LOCTYPE="URL" xlink:href="derivatives/12345679.tif"/>
            </file>
        </fileGrp>
    </fileSec>
    <structMap TYPE="ONE_TO_MANY_SOURCE">
        <div TYPE="SOURCE_ENTITIES" DMDID="dmd-0000001">
            <div TYPE="SOURCE_ENTITY" ID="bar">
                <mptr LOCTYPE="URL" xlink:href="parts/part.mets"/>
            </div>
            <div TYPE="SOURCE_ENTITY" ID="bar1">
                <mptr LOCTYPE="URL" xlink:href="parts/part1.mets"/>
            </div>
        </div>
    </structMap>
</mets>
